baseURL = "https://damnotes.netlify.com/"
languageCode = "en-us"
title = "DamNotes"

[permalinks]
    blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        pre = "user"
        url = "/about/"
        weight = 2
    [[menu.social]]
        name = "GitHub"
        pre = "github"
        url = "https://github.com/damianolodi"
        weight = 1
    [[menu.social]]
        name = "LinkedIn"
        pre = "linkedin"
        url = "https://www.linkedin.com/in/damiano-lodi/"
        weight = 2

[params]
    dateFormat = "Jan 2, 2006"
    homeText = "You just made a Hugo blog from scratch."

[taxonomies]
    tag = "tags"
