backend:
  name: git-gateway
  branch: master

media_folder: "static/img/cms-uploads"
public_folder: "/img"

collections:
  - name: "python" # Used in routes, e.g., /admin/collections/blog
    label: "Python" # Used in the UI
    folder: "python" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", required: true, default: false}
      - {label: "Arguments", name: "arguments", widget: "list", required: false, default: []}
      - {label: "Weight", name: "weight", widget: "number", required: true, default: 99}
